providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20", "fontconfig", "freetype", "zlib"]
nixLibs = ["fontconfig", "freetype", "zlib"]
aptPkgs = ["fontconfig", "libfreetype6", "libssl-dev", "bzip2", "phantomjs"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "npm start"
